import BackToTopButton from './components/BackToTopButton';
import ScriptLoader from './components/ScriptLoader';

export const metadata = {
  title: "Paypath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zxx">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* favicon */}
        <link rel="shortcut icon" href="/assets/images/favicon.png" type="image/x-icon" />
        {/* framework of css */}
        <link rel="stylesheet" href="/assets/css/bootstrap-lib/bootstrap.min.css" />
        {/* style sheet of css */}
        <link rel="stylesheet" href="/assets/css/style.css" />
        {/* Responsive sheet of css */}
        <link rel="stylesheet" href="/assets/css/responsive.css" />
        {/* fonts awesome icon link */}
        <link rel="stylesheet" href="/assets/font-awesome-lib/icon/font-awesome.min.css" />
        {/* slick-slider link css */}
        <link rel="stylesheet" href="/assets/css/slick.min.css" />
        {/* animation of css */}
        <link rel="stylesheet" href="/assets/css/aos.css" />
      </head>
      <body>
        {children}

        {/* button back to top */}
        <BackToTopButton />

        {/* JavaScript files */}
        <ScriptLoader />
      </body>
    </html>
  );
}
